package gestionDeTareas.GUI;

import gestionDeTareas.Logica.Usuario;
import gestionDeTareas.Logica.UsuarioDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author silva
 */
public class Usuarios extends javax.swing.JInternalFrame {
       
    // Variable global para el modo de edición
    public boolean modoEdicion = true;  
    // Usar el UsuarioDAO para validar
    UsuarioDAO usuarioDAO = new UsuarioDAO();
    
    /**
     * Creates new form Usuarios
     */
    
    public Usuarios() {
        initComponents();
        reiniciarEstadoPantalla() ;
           
    }
    
    // Método para llenar grilla con usuarios
    public void llenarGrilla(JTable tbUsuarios) {
        // Obtener el modelo de la tabla existente (creada desde el diseñador)
        DefaultTableModel modelo = (DefaultTableModel) tbUsuarios.getModel();

        // Limpiar cualquier fila existente en la tabla
        modelo.setRowCount(0);

        // Obtener los datos de los usuarios desde la base de datos
        List<Usuario> listaUsuarios = usuarioDAO.obtenerTodosUsuarios();

        // Recorrer la lista de usuarios y agregar cada uno al modelo
        for (Usuario usuario : listaUsuarios) {
            Object[] fila = {
                usuario.getId(),
                usuario.getNombre(),
                usuario.getApellido(),
                usuario.getUsuario(),
                usuario.getContraseña()
            };
            modelo.addRow(fila);
        }
    }
        
    // Método para limpiar los campos del formulario
    public void limpiarCampos() {
        txtId.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtUsuario.setText("");
        txtPass.setText("");
    }
    
    // Método para replicar los datos de la fila seleccionada
    private void llenarFormulario(boolean primero) {
        if (tbUsuarios.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "No hay usuarios disponibles.");
            return; // Salir del método si no hay filas
        }

        int selectedRow = tbUsuarios.getSelectedRow(); // Obtener la fila seleccionada

        if (primero) { // Si primero es true
            // Seleccionar la primera fila
            selectedRow = 0;
            tbUsuarios.setRowSelectionInterval(selectedRow, selectedRow); // Seleccionar la fila en la tabla
        }

        // Verificar nuevamente si hay una fila seleccionada después de la lógica anterior
        selectedRow = tbUsuarios.getSelectedRow(); // Obtener la fila seleccionada (puede ser la primera)

        // Asignar los valores de la fila seleccionada a los campos de texto
        if (selectedRow >= 0) {
            txtId.setText(tbUsuarios.getValueAt(selectedRow, 0).toString());
            txtNombre.setText(tbUsuarios.getValueAt(selectedRow, 1).toString());
            txtApellido.setText(tbUsuarios.getValueAt(selectedRow, 2).toString());
            txtUsuario.setText(tbUsuarios.getValueAt(selectedRow, 3).toString());
            txtPass.setText(tbUsuarios.getValueAt(selectedRow, 4).toString());
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, selecciona una fila.");
        }
    }

    // Mètodo para reiniciar pantalla
    private void reiniciarEstadoPantalla() {
        // Limpiar campos después de eliminar
        limpiarCampos();
        tbUsuarios.setEnabled(true);
        llenarGrilla(tbUsuarios); // Volver a llenar la tabla de usuarios después de eliminar
        llenarFormulario(true); // Seleccionar el primer usuario de la grilla
        this.modoEdicion = true;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtId = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        txtPass = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        scrollUsuarios = new javax.swing.JScrollPane();
        tbUsuarios = new javax.swing.JTable();
        Menu = new javax.swing.JMenuBar();
        menuNuevo = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuGuardar = new javax.swing.JMenu();
        menuCancelar = new javax.swing.JMenu();
        menuActualizar = new javax.swing.JMenu();
        menuEliminar = new javax.swing.JMenu();
        menuSalir = new javax.swing.JMenu();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Usuarios");

        txtId.setEditable(false);
        txtId.setToolTipText("");

        lblId.setText("Id");

        lblNombre.setText("Nombre");

        lblApellido.setText("Apellido");

        lblUsuario.setText("Usuario");

        lblPass.setText("Contraseña");

        tbUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Apellido", "Usuario", "Contraseña"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbUsuariosMouseClicked(evt);
            }
        });
        scrollUsuarios.setViewportView(tbUsuarios);

        menuNuevo.setText("Nuevo");
        menuNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuNuevoMouseClicked(evt);
            }
        });
        menuNuevo.add(jSeparator1);

        Menu.add(menuNuevo);

        menuGuardar.setText("Guardar");
        menuGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuGuardarMouseClicked(evt);
            }
        });
        Menu.add(menuGuardar);

        menuCancelar.setText("Cancelar");
        menuCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCancelarMouseClicked(evt);
            }
        });
        Menu.add(menuCancelar);

        menuActualizar.setText("Actualizar");
        menuActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuActualizarMouseClicked(evt);
            }
        });
        Menu.add(menuActualizar);

        menuEliminar.setText("Eliminar");
        menuEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuEliminarMouseClicked(evt);
            }
        });
        Menu.add(menuEliminar);

        menuSalir.setText("Salir");
        menuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSalirMouseClicked(evt);
            }
        });
        Menu.add(menuSalir);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblId)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblApellido)
                                .addGap(114, 114, 114)
                                .addComponent(lblUsuario)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPass)
                            .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(lblNombre)
                    .addComponent(lblApellido)
                    .addComponent(lblUsuario)
                    .addComponent(lblPass, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(scrollUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    private void menuCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCancelarMouseClicked
        // TODO add your handling code here:
        reiniciarEstadoPantalla(); // reinicio pantalla
    }//GEN-LAST:event_menuCancelarMouseClicked

    private void menuActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuActualizarMouseClicked
        // TODO add your handling code here:
        llenarGrilla(tbUsuarios);
        this.modoEdicion = true;
    }//GEN-LAST:event_menuActualizarMouseClicked

    private void menuSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSalirMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_menuSalirMouseClicked

    private void menuEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuEliminarMouseClicked
        // TODO add your handling code here:
        // Obtener el ID del usuario a eliminar desde el campo de texto
        String idText = txtId.getText();

        if (idText.isEmpty()) {
            // Si el campo de ID está vacío, mostrar un mensaje de error
            JOptionPane.showMessageDialog(this, "Por favor, ingresa un Id válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Salir del método
        }

        int id = Integer.parseInt(idText); // Convertir el Id a entero

        // Mostrar un mensaje de advertencia antes de eliminar
        int respuesta = JOptionPane.showConfirmDialog(this, "¿Estás seguro de que deseas eliminar este usuario?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);

        if (respuesta == JOptionPane.YES_OPTION) {
            // Si el usuario confirma, proceder a eliminar
            usuarioDAO.eliminarUsuario(id);
            JOptionPane.showMessageDialog(this, "Usuario eliminado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

            // Opcional: Llamar a llenarGrilla para actualizar la tabla después de eliminar
            llenarGrilla(tbUsuarios);
        } else {
            // El usuario canceló la eliminación
            JOptionPane.showMessageDialog(this, "Eliminación cancelada.", "Cancelado", JOptionPane.INFORMATION_MESSAGE);
        }
        
        reiniciarEstadoPantalla();//reiniciar pantalla
    }//GEN-LAST:event_menuEliminarMouseClicked

    private void menuNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuNuevoMouseClicked
        // TODO add your handling code here:
        limpiarCampos();
        this.modoEdicion = false;
        tbUsuarios.setEnabled(false);
        
    }//GEN-LAST:event_menuNuevoMouseClicked

    private void menuGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuGuardarMouseClicked
        // Obtener los datos de los campos de texto
        String nombre = txtNombre.getText();
        String apellido = txtApellido.getText();
        String usuario = txtUsuario.getText();
        String contraseña = txtPass.getText();
    
        // Verificar si estamos en modo de edición o no
        if (this.modoEdicion) {
            // Modo de edición: Actualizar el usuario existente
            int id = Integer.parseInt(txtId.getText()); // Obtener el ID del usuario a editar
            Usuario usuarioActualizado = new Usuario(id, nombre, apellido, usuario, contraseña);
            usuarioDAO.actualizarUsuario(usuarioActualizado);
            JOptionPane.showMessageDialog(this, "Usuario actualizado correctamente.");
        } else {
            // Modo de creación: Agregar un nuevo usuario
            Usuario nuevoUsuario = new Usuario(null,nombre, apellido, usuario, contraseña);
            usuarioDAO.agregarUsuario(nuevoUsuario);
            JOptionPane.showMessageDialog(this, "Usuario agregado correctamente.");
        }

        reiniciarEstadoPantalla();//reiniciar pantalla
    }//GEN-LAST:event_menuGuardarMouseClicked

    private void tbUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbUsuariosMouseClicked
        // TODO add your handling code here:
        // controlo que la grilla este habilitada
        if (tbUsuarios.isEnabled() == true){
             llenarFormulario(false);
        }
      
    }//GEN-LAST:event_tbUsuariosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Menu;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    public javax.swing.JLabel lblApellido;
    public javax.swing.JLabel lblId;
    public javax.swing.JLabel lblNombre;
    public javax.swing.JLabel lblPass;
    public javax.swing.JLabel lblUsuario;
    private javax.swing.JMenu menuActualizar;
    private javax.swing.JMenu menuCancelar;
    private javax.swing.JMenu menuEliminar;
    private javax.swing.JMenu menuGuardar;
    private javax.swing.JMenu menuNuevo;
    private javax.swing.JMenu menuSalir;
    private javax.swing.JScrollPane scrollUsuarios;
    public javax.swing.JTable tbUsuarios;
    public javax.swing.JTextField txtApellido;
    public javax.swing.JTextField txtId;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtPass;
    public javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
